// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpbfexyyjhzxtkhrclpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwYmZleHl5amh6eHRraHJjbHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNTk2NTYsImV4cCI6MjA1NjYzNTY1Nn0.wdKlSc7hU7yJziCUH0dFo78d2D4DOcy6T7axnqkR3_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);